ignore_patterns:
  directories:
  - .git
  - .github
  - __pycache__
  - node_modules
  - venv
  - .venv
  - env
  - .env
  - build
  - dist
  - .idea
  - .vscode
  - vendor
  - site-packages
  - tests
  - docs
  files:
  - '*.pyc'
  - '*.pyo'
  - '*.pyd'
  - '*.so'
  - '*.dll'
  - '*.dylib'
  - '*.egg-info'
  - '*.egg'
  - '*.whl'
  - .DS_Store
  - Thumbs.db
  - '*.log'
  - .env
  - .gitignore
  - '*.lock'
  - package-lock.json
  - '*.md'
  - '*.test.js'
included_extensions:
- .ipynb
- .html
- .css
- .js
- .jsx
- .md
- .rst
- .py
- .*
local_root: C:\Github\ticket_tracker\ticket_tracker
logging:
  datefmt: '%Y-%m-%d %H:%M:%S'
  format: '%(asctime)s - %(levelname)s - %(message)s'
  level: INFO
output_directory: prompts
output_filename: ticket_tracker_prompt.txt
